/**
 * SEO hub clusters — homepage footer discovery (not in super menu)
 */

export type SeoHubCluster = {
  id: string;
  slug: string;
  path: string;
  titleEn: string;
  titleHi: string;
  descriptionEn: string;
  descriptionHi: string;
  keywords: string[];
  links: { labelEn: string; labelHi: string; href: string }[];
};

export const SEO_HOMEPAGE_CLUSTERS: SeoHubCluster[] = [
  {
    id: "jobs",
    slug: "jobs",
    path: "/category/jobs",
    titleEn: "Jobs & Careers",
    titleHi: "नौकरी और करियर",
    descriptionEn:
      "Latest government jobs, private vacancies, and career news for Chhattisgarh youth.",
    descriptionHi:
      "छत्तीसगढ़ युवाओं के लिए सरकारी नौकरी, प्राइवेट वैकेंसी और करियर खबरें।",
    keywords: ["CG jobs", "sarkari naukri", "रायपुर नौकरी"],
    links: [
      { labelEn: "All jobs", labelHi: "सभी नौकरी", href: "/search?q=jobs" },
      { labelEn: "Government", labelHi: "सरकारी", href: "/search?q=sarkari" },
    ],
  },
  {
    id: "yojana",
    slug: "sarkari-yojana",
    path: "/search?q=sarkari+yojana",
    titleEn: "Sarkari Yojana",
    titleHi: "सरकारी योजना",
    descriptionEn: "Schemes, subsidies, and welfare updates for Chhattisgarh residents.",
    descriptionHi: "छत्तीसगढ़ निवासियों के लिए योजना, सब्सिडी और लाभ अपडेट।",
    keywords: ["yojana CG", "welfare scheme"],
    links: [
      { labelEn: "Latest schemes", labelHi: "नई योजनाएँ", href: "/search?q=yojana" },
    ],
  },
  {
    id: "gold",
    slug: "gold-silver",
    path: "/search?q=gold+rate+chhattisgarh",
    titleEn: "Gold & Silver Rates",
    titleHi: "सोना चाँदी भाव",
    descriptionEn: "Daily gold and silver prices with CG market context.",
    descriptionHi: "रोज़ाना सोना-चाँदी के भाव छत्तीसगढ़ संदर्भ के साथ।",
    keywords: ["gold rate Raipur", "silver price CG"],
    links: [
      { labelEn: "Gold today", labelHi: "आज सोना", href: "/search?q=gold" },
      { labelEn: "Silver", labelHi: "चाँदी", href: "/search?q=silver" },
    ],
  },
  {
    id: "stocks",
    slug: "stock-market",
    path: "/search?q=stock+market",
    titleEn: "Stock Market",
    titleHi: "शेयर बाजार",
    descriptionEn: "Nifty, Sensex, and Indian stock movers explained for readers.",
    descriptionHi: "निफ्टी, सेंसेक्स और शेयर बाजार की खबरें सरल भाषा में।",
    keywords: ["Nifty 50", "Sensex today", "share market Hindi"],
    links: [
      { labelEn: "Market live", labelHi: "मार्केट लाइव", href: "/search?q=nifty" },
      { labelEn: "Business desk", labelHi: "बिज़नेस", href: "/category/business" },
    ],
  },
  {
    id: "ai-news",
    slug: "ai-news",
    path: "/search?q=artificial+intelligence",
    titleEn: "AI News",
    titleHi: "AI समाचार",
    descriptionEn: "Artificial intelligence, startups, and tech policy from India and CG.",
    descriptionHi: "कृत्रिम बुद्धिमत्ता, स्टार्टअप और टेक नीति की खबरें।",
    keywords: ["AI news India", "tech AI Hindi"],
    links: [
      { labelEn: "Technology", labelHi: "टेक", href: "/category/technology" },
      { labelEn: "Startups", labelHi: "स्टार्टअप", href: "/search?q=startup" },
    ],
  },
  {
    id: "gadgets",
    slug: "gadgets",
    path: "/search?q=gadgets",
    titleEn: "Gadgets",
    titleHi: "गैजेट्स",
    descriptionEn: "Mobile, gadgets, and consumer tech reviews and launches.",
    descriptionHi: "मोबाइल, गैजेट और कंज्यूमर टेक लॉन्च।",
    keywords: ["mobile news", "gadget review Hindi"],
    links: [{ labelEn: "Tech news", labelHi: "टेक खबर", href: "/category/technology" }],
  },
  {
    id: "weather",
    slug: "weather",
    path: "/search?q=weather+chhattisgarh",
    titleEn: "Weather",
    titleHi: "मौसम",
    descriptionEn: "Raipur, Bilaspur, and district weather alerts and forecasts.",
    descriptionHi: "रायपुर, बिलासपुर और जिलों का मौसम अलर्ट।",
    keywords: ["CG weather", "monsoon Chhattisgarh"],
    links: [
      { labelEn: "Rain alert", labelHi: "बारिश", href: "/search?q=rain" },
    ],
  },
  {
    id: "agriculture",
    slug: "agriculture",
    path: "/category/agriculture",
    titleEn: "Agriculture & Mandi",
    titleHi: "कृषि और मंडी",
    descriptionEn: "Crop prices, mandi rates, and farming policy for CG farmers.",
    descriptionHi: "फसल भाव, मंडी दर और किसान नीति।",
    keywords: ["mandi rate", "kisan news CG"],
    links: [
      { labelEn: "Agriculture desk", labelHi: "कृषि डेस्क", href: "/category/agriculture" },
    ],
  },
  {
    id: "education",
    slug: "education",
    path: "/category/education",
    titleEn: "Education",
    titleHi: "शिक्षा",
    descriptionEn: "Board exams, university, scholarships, and school news.",
    descriptionHi: "बोर्ड परीक्षा, विश्वविद्यालय, छात्रवृत्ति और स्कूल खबरें।",
    keywords: ["CG education news", "exam result"],
    links: [
      { labelEn: "Education", labelHi: "शिक्षा", href: "/category/education" },
    ],
  },
  {
    id: "districts",
    slug: "district-news",
    path: "/category/chhattisgarh",
    titleEn: "Local District News",
    titleHi: "जिला समाचार",
    descriptionEn: "Hyperlocal coverage from every major CG district bureau.",
    descriptionHi: "हर बड़े जिले की हाइपरलोकल कवरेज।",
    keywords: ["Raipur news", "Bastar news", "Bilaspur samachar"],
    links: [
      { labelEn: "Raipur", labelHi: "रायपुर", href: "/district/raipur" },
      { labelEn: "Bilaspur", labelHi: "बिलासपुर", href: "/district/bilaspur" },
      { labelEn: "Bastar", labelHi: "बस्तर", href: "/district/bastar" },
    ],
  },
  {
    id: "crime",
    slug: "crime",
    path: "/category/crime",
    titleEn: "Crime",
    titleHi: "अपराध",
    descriptionEn: "Crime, court, and public safety reporting across the state.",
    descriptionHi: "अपराध, कोर्ट और लोक सुरक्षा रिपोर्टिंग।",
    keywords: ["CG crime news", "police bulletin"],
    links: [{ labelEn: "Crime desk", labelHi: "क्राइम", href: "/category/crime" }],
  },
  {
    id: "elections",
    slug: "elections",
    path: "/search?q=election",
    titleEn: "Elections",
    titleHi: "चुनाव",
    descriptionEn: "Election tracker, results, and political analysis for CG and India.",
    descriptionHi: "चुनाव ट्रैकर, परिणाम और राजनीतिक विश्लेषण।",
    keywords: ["Chhattisgarh election", "vote news"],
    links: [
      { labelEn: "Politics", labelHi: "राजनीति", href: "/category/politics" },
    ],
  },
  {
    id: "viral",
    slug: "viral",
    path: "/search?q=viral",
    titleEn: "Viral",
    titleHi: "वायरल",
    descriptionEn: "Trending viral stories, social media moments, and web culture.",
    descriptionHi: "ट्रेंडिंग वायरल कहानियाँ और सोशल मीडिया।",
    keywords: ["viral news Hindi", "trending CG"],
    links: [{ labelEn: "Reels", labelHi: "रील्स", href: "/shorts" }],
  },
  {
    id: "fact-check",
    slug: "fact-check",
    path: "/fact-check-policy",
    titleEn: "Fact Check",
    titleHi: "फैक्ट चेक",
    descriptionEn: "Verified reporting standards and misinformation debunks.",
    descriptionHi: "सत्यापित रिपोर्टिंग और गलत सूचना की जाँच।",
    keywords: ["fact check Hindi", "fake news CG"],
    links: [
      {
        labelEn: "Fact check policy",
        labelHi: "फैक्ट चेक नीति",
        href: "/fact-check-policy",
      },
    ],
  },
  {
    id: "live-tv",
    slug: "live-tv",
    path: "/search?q=live+tv",
    titleEn: "Live TV",
    titleHi: "लाइव टीवी",
    descriptionEn: "Live TV updates, breaking broadcast, and stream highlights.",
    descriptionHi: "लाइव टीवी अपडेट और ब्रेकिंग प्रसारण।",
    keywords: ["live TV news", "breaking live"],
    links: [{ labelEn: "Live desk", labelHi: "लाइव", href: "/live" }],
  },
  {
    id: "horoscope",
    slug: "horoscope",
    path: "/search?q=horoscope",
    titleEn: "Horoscope",
    titleHi: "राशिफल",
    descriptionEn: "Daily rashifal and astrology reads for regional audiences.",
    descriptionHi: "दैनिक राशिफल और ज्योतिष।",
    keywords: ["aaj ka rashifal", "horoscope Hindi"],
    links: [{ labelEn: "Today rashifal", labelHi: "आज राशिफल", href: "/search?q=rashifal" }],
  },
  {
    id: "web-stories",
    slug: "web-stories",
    path: "/shorts",
    titleEn: "Web Stories & Reels",
    titleHi: "वेब स्टोरी और रील्स",
    descriptionEn: "Vertical news reels and visual story formats.",
    descriptionHi: "वर्टिकल न्यूज़ रील्स और विज़ुअल फ़ॉर्मैट।",
    keywords: ["news reels", "web story CG"],
    links: [{ labelEn: "Watch reels", labelHi: "रील्स देखें", href: "/shorts" }],
  },
  {
    id: "auto",
    slug: "auto",
    path: "/search?q=auto",
    titleEn: "Auto",
    titleHi: "ऑटो",
    descriptionEn: "Cars, bikes, EV, and transport policy news.",
    descriptionHi: "कार, बाइक, EV और परिवहन खबरें।",
    keywords: ["auto news India", "EV CG"],
    links: [{ labelEn: "Auto search", labelHi: "ऑटो", href: "/search?q=auto" }],
  },
  {
    id: "real-estate",
    slug: "real-estate",
    path: "/search?q=real+estate",
    titleEn: "Real Estate",
    titleHi: "रियल एस्टेट",
    descriptionEn: "Property, housing, and Raipur real estate trends.",
    descriptionHi: "प्रॉपर्टी, आवास और रायपुर रियल एस्टेट।",
    keywords: ["Raipur property", "CG real estate"],
    links: [{ labelEn: "Property news", labelHi: "प्रॉपर्टी", href: "/search?q=property" }],
  },
  {
    id: "tourism",
    slug: "tourism",
    path: "/search?q=tourism+bastar",
    titleEn: "Tourism",
    titleHi: "पर्यटन",
    descriptionEn: "Bastar, Chitrakote, and CG tourism guides and alerts.",
    descriptionHi: "बस्तर, चित्रकोट और छत्तीसगढ़ पर्यटन।",
    keywords: ["Bastar tourism", "CG travel"],
    links: [{ labelEn: "Bastar", labelHi: "बस्तर", href: "/district/bastar" }],
  },
  {
    id: "health",
    slug: "health",
    path: "/search?q=health",
    titleEn: "Health",
    titleHi: "स्वास्थ्य",
    descriptionEn: "Health desk, hospitals, and public health updates.",
    descriptionHi: "स्वास्थ्य डेस्क, अस्पताल और सार्वजनिक स्वास्थ्य।",
    keywords: ["health news CG", "disease alert"],
    links: [{ labelEn: "Health search", labelHi: "स्वास्थ्य", href: "/search?q=health" }],
  },
  {
    id: "cricket",
    slug: "ipl-cricket",
    path: "/search?q=cricket",
    titleEn: "IPL & Cricket",
    titleHi: "IPL और क्रिकेट",
    descriptionEn: "Cricket scores, IPL, and Team India updates.",
    descriptionHi: "क्रिकेट स्कोर, IPL और टीम इंडिया अपडेट।",
    keywords: ["IPL news", "cricket Hindi"],
    links: [
      { labelEn: "Sports", labelHi: "खेल", href: "/category/sports" },
      { labelEn: "Live cricket", labelHi: "लाइव क्रिकेट", href: "/search?q=cricket+live" },
    ],
  },
];
