import { defaultMonetizationSettings } from "@/lib/monetization/placements";
import type { TenantConfig } from "@/lib/tenant/types";

const SITE =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://newspaper-motion.vercel.app";

/** Default tenant — current CG Bhaskar product */
export const CG_BHASKAR_TENANT: TenantConfig = {
  version: 1,
  id: "00000000-0000-4000-8000-000000000001",
  slug: "cg-bhaskar",
  status: "active",
  domains: [
    "localhost",
    "127.0.0.1",
    "newspaper-motion.vercel.app",
    new URL(SITE).hostname,
  ].filter(Boolean),
  siteUrl: SITE,
  branding: {
    nameEn: "CG Bhaskar",
    nameHi: "सीजी भास्कर",
    taglineEn: "Chhattisgarh's journal of record",
    taglineHi: "छत्तीसगढ़ का विश्वसनीय अखबार",
    logoUrl: "/brand/cg-bhaskar-logo.svg",
    logoMarkUrl: "/brand/cg-bhaskar-mark.svg",
    faviconUrl: "/favicon.ico",
    conceptLabel: "AI Newsroom",
  },
  typography: {
    fontDisplay: "Playfair Display",
    fontBody: "Source Serif 4",
    fontMeta: "DM Mono",
    fontRegional: "Noto Serif Devanagari",
  },
  theme: {
    primary: "#7f1d1d",
    primaryDark: "#450a0a",
    accent: "#b45309",
    accentSoft: "#fef3e8",
    live: "#dc2626",
    liveSoft: "#fef2f2",
    surface: "#fafafa",
    ink: "#1c1c1e",
  },
  categories: [
    {
      id: "top-news",
      slug: "top-news",
      label: "Top News",
      labelHi: "टॉप",
      href: "#top-news",
      matchers: [],
      navOrder: 0,
    },
    {
      id: "chhattisgarh",
      slug: "chhattisgarh",
      label: "Chhattisgarh",
      labelHi: "छत्तीसगढ़",
      sectionId: "chhattisgarh",
      href: "/category/chhattisgarh",
      matchers: [/chhattisgarh/i, /छत्तीसगढ/i, /bastar/i],
      navOrder: 1,
    },
    {
      id: "raipur",
      slug: "raipur",
      label: "Raipur",
      labelHi: "रायपुर",
      sectionId: "raipur",
      href: "/category/raipur",
      matchers: [/raipur/i, /रायपुर/i],
      navOrder: 2,
    },
    {
      id: "politics",
      slug: "politics",
      label: "Politics",
      labelHi: "राजनीति",
      sectionId: "india",
      href: "/category/politics",
      matchers: [/politics/i, /election/i, /विधान/i],
      navOrder: 3,
    },
    {
      id: "business",
      slug: "business",
      label: "Business",
      labelHi: "व्यापार",
      sectionId: "business",
      href: "/category/business",
      matchers: [/business/i, /economy/i, /व्यापार/i],
      navOrder: 4,
    },
    {
      id: "sports",
      slug: "sports",
      label: "Sports",
      labelHi: "खेल",
      sectionId: "sports",
      href: "/category/sports",
      matchers: [/sport/i, /cricket/i, /खेल/i],
      navOrder: 5,
    },
    {
      id: "education",
      slug: "education",
      label: "Education",
      labelHi: "शिक्षा",
      sectionId: "education",
      href: "/category/education",
      matchers: [/education/i, /school/i, /शिक्षा/i],
      navOrder: 6,
    },
  ],
  regions: [
    {
      slug: "chhattisgarh",
      name: "Chhattisgarh",
      nameHi: "छत्तीसगढ़",
      priority: 1,
      routingWeight: 1,
      isPrimary: true,
    },
    {
      slug: "raipur",
      name: "Raipur",
      nameHi: "रायपुर",
      priority: 1,
      routingWeight: 0.95,
    },
    {
      slug: "bilaspur",
      name: "Bilaspur",
      nameHi: "बिलासपुर",
      priority: 1,
      routingWeight: 0.9,
    },
    {
      slug: "durg",
      name: "Durg-Bhilai",
      nameHi: "दुर्ग-भिलाई",
      priority: 1,
      routingWeight: 0.88,
    },
  ],
  newsroom: {
    defaultLanguage: "hi",
    enabledLanguages: ["hi", "en", "cg", "mr", "bn", "ta"],
    primaryRegionSlug: "chhattisgarh",
    regionalFirst: true,
    regionalBoostMultiplier: 1.15,
    timezone: "Asia/Kolkata",
    headerCity: "Raipur",
    headerCityHi: "रायपुर",
    editionLabel: "Statewide",
  },
  seo: {
    titleSuffix: "Chhattisgarh News",
    defaultDescription:
      "Premium regional news from Chhattisgarh — calm, fast, and trustworthy. AI-edited stories from Raipur, Bastar, Bilaspur, and across the state.",
    keywords: [
      "CG Bhaskar",
      "Chhattisgarh news",
      "Raipur news",
      "Bastar",
      "Bilaspur",
      "छत्तीसगढ़ समाचार",
      "regional news India",
    ],
    locale: "hi_IN",
  },
  monetization: defaultMonetizationSettings(),
  updatedAt: new Date().toISOString(),
};
