import { defaultMonetizationSettings } from "@/lib/monetization/placements";
import type { TenantConfig } from "@/lib/tenant/types";

const SITE =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://newspaper-motion.vercel.app";

/** Hamar Chhattisgarh — original regional media identity (not affiliated with any national daily) */
export const HAMAR_CHHATTISGARH_TENANT: TenantConfig = {
  version: 1,
  id: "00000000-0000-4000-8000-000000000002",
  slug: "hamar-chhattisgarh",
  status: "active",
  domains: [
    "localhost",
    "127.0.0.1",
    "newspaper-motion.vercel.app",
    new URL(SITE).hostname,
  ].filter(Boolean),
  siteUrl: SITE,
  branding: {
    nameEn: "Hamar Chhattisgarh",
    nameHi: "हमार छत्तीसगढ़",
    taglineEn: "Chhattisgarh's own digital newspaper",
    taglineHi: "छत्तीसगढ़ का अपना डिजिटल अखबार",
    logoUrl: "/brand/hamar-chhattisgarh-logo.svg",
    logoMarkUrl: "/brand/hamar-chhattisgarh-mark.svg",
    faviconUrl: "/brand/hamar-chhattisgarh-mark.svg",
    conceptLabel: "Regional Digital News",
  },
  typography: {
    fontDisplay: "Noto Serif Devanagari",
    fontBody: "Source Serif 4",
    fontMeta: "DM Mono",
    fontRegional: "Noto Serif Devanagari",
  },
  theme: {
    primary: "#1a4d3e",
    primaryDark: "#0f2e26",
    accent: "#c45c2a",
    accentSoft: "#f5ebe0",
    live: "#d64545",
    liveSoft: "#fdecec",
    surface: "#faf9f7",
    ink: "#1a1a1c",
  },
  categories: [
    {
      id: "top-news",
      slug: "top-news",
      label: "Top News",
      labelHi: "टॉप",
      href: "/",
      matchers: [],
      navOrder: 0,
    },
    {
      id: "chhattisgarh",
      slug: "chhattisgarh",
      label: "Chhattisgarh",
      labelHi: "छत्तीसगढ़",
      sectionId: "chhattisgarh",
      href: "/category/chhattisgarh",
      matchers: [/chhattisgarh/i, /छत्तीसगढ/i, /bastar/i],
      navOrder: 1,
    },
    {
      id: "raipur",
      slug: "raipur",
      label: "Raipur",
      labelHi: "रायपुर",
      sectionId: "raipur",
      href: "/category/raipur",
      matchers: [/raipur/i, /रायपुर/i],
      navOrder: 2,
    },
    {
      id: "politics",
      slug: "politics",
      label: "Politics",
      labelHi: "राजनीति",
      sectionId: "india",
      href: "/category/politics",
      matchers: [/politics/i, /election/i, /विधान/i],
      navOrder: 3,
    },
    {
      id: "business",
      slug: "business",
      label: "Business",
      labelHi: "व्यापार",
      sectionId: "business",
      href: "/category/business",
      matchers: [/business/i, /economy/i, /व्यापार/i],
      navOrder: 4,
    },
    {
      id: "sports",
      slug: "sports",
      label: "Sports",
      labelHi: "खेल",
      sectionId: "sports",
      href: "/category/sports",
      matchers: [/sport/i, /cricket/i, /खेल/i],
      navOrder: 5,
    },
    {
      id: "education",
      slug: "education",
      label: "Education",
      labelHi: "शिक्षा",
      sectionId: "education",
      href: "/category/education",
      matchers: [/education/i, /school/i, /शिक्षा/i],
      navOrder: 6,
    },
  ],
  regions: [
    {
      slug: "chhattisgarh",
      name: "Chhattisgarh",
      nameHi: "छत्तीसगढ़",
      priority: 1,
      routingWeight: 1,
      isPrimary: true,
    },
    {
      slug: "raipur",
      name: "Raipur",
      nameHi: "रायपुर",
      priority: 1,
      routingWeight: 0.95,
    },
    {
      slug: "bilaspur",
      name: "Bilaspur",
      nameHi: "बिलासपुर",
      priority: 1,
      routingWeight: 0.9,
    },
    {
      slug: "durg",
      name: "Durg-Bhilai",
      nameHi: "दुर्ग-भिलाई",
      priority: 1,
      routingWeight: 0.88,
    },
    {
      slug: "bastar",
      name: "Bastar",
      nameHi: "बस्तर",
      priority: 2,
      routingWeight: 0.82,
    },
    {
      slug: "korba",
      name: "Korba",
      nameHi: "कोरबा",
      priority: 2,
      routingWeight: 0.8,
    },
  ],
  newsroom: {
    defaultLanguage: "hi",
    enabledLanguages: ["hi", "en", "cg", "mr", "bn", "ta"],
    primaryRegionSlug: "chhattisgarh",
    regionalFirst: true,
    regionalBoostMultiplier: 1.15,
    timezone: "Asia/Kolkata",
    headerCity: "Raipur",
    headerCityHi: "रायपुर",
    editionLabel: "आज का अंक",
  },
  seo: {
    titleSuffix: "छत्तीसगढ़ समाचार",
    defaultDescription:
      "हमार छत्तीसगढ़ — रायपुर, बिलासपुर, बस्तर और सभी जिलों की ताज़ा, विश्वसनीय खबरें। हिंदी में, आपके लिए।",
    keywords: [
      "Hamar Chhattisgarh",
      "हमार छत्तीसगढ़",
      "Chhattisgarh news",
      "Raipur news",
      "Bilaspur news",
      "Bastar news",
      "छत्तीसगढ़ समाचार",
      "रायपुर न्यूज़",
      "छत्तीसगढ़ी खबर",
    ],
    locale: "hi_IN",
  },
  monetization: defaultMonetizationSettings(),
  updatedAt: new Date().toISOString(),
};
