import { JAN_DARPAN_BRAND_ASSETS } from "@/lib/brand/assets";
import { defaultMonetizationSettings } from "@/lib/monetization/placements";
import {
  resolveCanonicalSiteHostname,
  resolveCanonicalSiteUrl,
} from "@/lib/seo/canonical-url";
import type { TenantConfig } from "@/lib/tenant/types";

const SITE_URL = resolveCanonicalSiteUrl();
const SITE_HOSTNAME = resolveCanonicalSiteHostname();

/** Jan Darpan Chhattisgarh — official regional digital news identity */
export const JAN_DARPAN_CHHATTISGARH_TENANT: TenantConfig = {
  version: 1,
  id: "00000000-0000-4000-8000-000000000003",
  slug: "jan-darpan-chhattisgarh",
  status: "active",
  domains: [
    "localhost",
    "127.0.0.1",
    "newspaper-motion.vercel.app",
    SITE_HOSTNAME,
  ].filter(Boolean),
  siteUrl: SITE_URL,
  branding: {
    nameEn: "Jan Darpan — India",
    nameHi: "जन दर्पण — भारत",
    shortNameEn: "Jan Darpan",
    shortNameHi: "जन दर्पण",
    taglineEn: "India's premier digital news platform",
    taglineHi: "भारत का अग्रणी डिजिटल समाचार मंच",
    logoUrl: JAN_DARPAN_BRAND_ASSETS.logo,
    logoMarkUrl: JAN_DARPAN_BRAND_ASSETS.mark,
    faviconUrl: JAN_DARPAN_BRAND_ASSETS.mark,
    ogImageUrl: JAN_DARPAN_BRAND_ASSETS.og,
    conceptLabel: "National Digital News",
  },
  typography: {
    fontDisplay: "Playfair Display",
    fontBody: "Source Serif 4",
    fontMeta: "DM Mono",
    fontRegional: "Noto Serif Devanagari",
  },
  theme: {
    primary: "#c62828",
    primaryDark: "#5c1616",
    accent: "#c5a07d",
    accentSoft: "#f3ebe0",
    live: "#dc2626",
    liveSoft: "#fdecec",
    surface: "#f7f7f7",
    ink: "#1a1a1a",
  },
  categories: [
    {
      id: "top-news",
      slug: "top-news",
      label: "Top News",
      labelHi: "टॉप",
      href: "/",
      matchers: [],
      navOrder: 0,
    },
    {
      id: "india",
      slug: "india",
      label: "National",
      labelHi: "देश",
      sectionId: "india",
      href: "/category/india",
      matchers: [/india/i, /bharat/i, /national/i, /देश/i, /भारत/i],
      navOrder: 1,
    },
    {
      id: "politics",
      slug: "politics",
      label: "Politics",
      labelHi: "राजनीति",
      sectionId: "india",
      href: "/category/politics",
      matchers: [/politics/i, /election/i, /संसद/i, /सरकार/i, /राजनीति/i],
      navOrder: 2,
    },
    {
      id: "business",
      slug: "business",
      label: "Business",
      labelHi: "व्यापार",
      sectionId: "business",
      href: "/category/business",
      matchers: [/business/i, /economy/i, /market/i, /व्यापार/i, /शेयर/i],
      navOrder: 3,
    },
    {
      id: "technology",
      slug: "technology",
      label: "Tech & AI",
      labelHi: "तकनीक",
      sectionId: "business",
      href: "/category/technology",
      matchers: [/tech/i, /ai/i, /mobile/i, /smartphone/i, /तकनीक/i],
      navOrder: 4,
    },
    {
      id: "education",
      slug: "education",
      label: "Jobs & Education",
      labelHi: "शिक्षा व नौकरी",
      sectionId: "education",
      href: "/category/education",
      matchers: [/education/i, /job/i, /exam/i, /naukri/i, /शिक्षा/i, /नौकरी/i],
      navOrder: 5,
    },
    {
      id: "sports",
      slug: "sports",
      label: "Sports",
      labelHi: "खेल",
      sectionId: "sports",
      href: "/category/sports",
      matchers: [/sport/i, /cricket/i, /खेल/i],
      navOrder: 6,
    },
  ],
  regions: [
    {
      slug: "india",
      name: "India",
      nameHi: "भारत",
      priority: 1,
      routingWeight: 1,
      isPrimary: true,
    },
    {
      slug: "delhi",
      name: "Delhi NCR",
      nameHi: "दिल्ली एनसीआर",
      priority: 1,
      routingWeight: 0.95,
    },
    {
      slug: "mumbai",
      name: "Mumbai",
      nameHi: "मुंबई",
      priority: 1,
      routingWeight: 0.9,
    },
  ],
  newsroom: {
    defaultLanguage: "hi",
    enabledLanguages: ["hi", "en"],
    primaryRegionSlug: "india",
    regionalFirst: false,
    regionalBoostMultiplier: 1.0,
    timezone: "Asia/Kolkata",
    headerCity: "New Delhi",
    headerCityHi: "नई दिल्ली",
    editionLabel: "आज का अंक",
  },
  seo: {
    titleSuffix: "जन दर्पण — भारत | Jan Darpan — India",
    defaultDescription:
      "जन दर्पण — भारत: देश, राष्ट्रीय राजनीति, व्यापार, तकनीक, रोजगार और प्रमुख घटनाक्रमों की ताज़ा और प्रामाणिक खबरें।",
    keywords: [
      "Jan Darpan — India",
      "जन दर्पण — भारत",
      "Jan Darpan",
      "जन दर्पण",
      "India news",
      "National news India",
      "Breaking news India",
      "Top news in India",
      "भारत समाचार",
      "देश की ताज़ा खबरें",
      "हिंदी समाचार",
    ],
    locale: "hi_IN",
  },
  monetization: defaultMonetizationSettings(),
  updatedAt: new Date().toISOString(),
};
