import { JAN_DARPAN_BRAND_ASSETS } from "@/lib/brand/assets";
import { defaultMonetizationSettings } from "@/lib/monetization/placements";
import {
  resolveCanonicalSiteHostname,
  resolveCanonicalSiteUrl,
} from "@/lib/seo/canonical-url";
import type { TenantConfig } from "@/lib/tenant/types";

const SITE_URL = resolveCanonicalSiteUrl();
const SITE_HOSTNAME = resolveCanonicalSiteHostname();

/** Jan Darpan — Chhattisgarh-rooted digital news platform expanding across India */
export const JAN_DARPAN_CHHATTISGARH_TENANT: TenantConfig = {
  version: 1,
  id: "00000000-0000-4000-8000-000000000003",
  slug: "jan-darpan-chhattisgarh",
  status: "active",
  domains: [
    "localhost",
    "127.0.0.1",
    "newspaper-motion.vercel.app",
    SITE_HOSTNAME,
  ].filter(Boolean),
  siteUrl: SITE_URL,
  branding: {
    nameEn: "Jan Darpan",
    nameHi: "जन दर्पण",
    shortNameEn: "Jan Darpan",
    shortNameHi: "जन दर्पण",
    taglineEn: "A Chhattisgarh-rooted digital news platform expanding across India",
    taglineHi: "छत्तीसगढ़ से देश तक — निष्पक्ष और प्रामाणिक डिजिटल समाचार",
    logoUrl: JAN_DARPAN_BRAND_ASSETS.logo,
    logoMarkUrl: JAN_DARPAN_BRAND_ASSETS.mark,
    faviconUrl: JAN_DARPAN_BRAND_ASSETS.mark,
    ogImageUrl: JAN_DARPAN_BRAND_ASSETS.og,
    conceptLabel: "Chhattisgarh & National News",
  },
  typography: {
    fontDisplay: "Playfair Display",
    fontBody: "Source Serif 4",
    fontMeta: "DM Mono",
    fontRegional: "Noto Serif Devanagari",
  },
  theme: {
    primary: "#c62828",
    primaryDark: "#5c1616",
    accent: "#c5a07d",
    accentSoft: "#f3ebe0",
    live: "#dc2626",
    liveSoft: "#fdecec",
    surface: "#f7f7f7",
    ink: "#1a1a1a",
  },
  categories: [
    {
      id: "top-news",
      slug: "top-news",
      label: "Top News",
      labelHi: "टॉप",
      href: "/",
      matchers: [],
      navOrder: 0,
    },
    {
      id: "chhattisgarh",
      slug: "chhattisgarh",
      label: "Chhattisgarh",
      labelHi: "छत्तीसगढ़",
      sectionId: "chhattisgarh",
      href: "/category/chhattisgarh",
      matchers: [/chhattisgarh/i, /छत्तीसगढ/i, /bastar/i, /raipur/i, /bilaspur/i],
      navOrder: 1,
    },
    {
      id: "india",
      slug: "india",
      label: "India",
      labelHi: "देश",
      sectionId: "india",
      href: "/category/india",
      matchers: [/india/i, /bharat/i, /national/i, /देश/i, /भारत/i],
      navOrder: 2,
    },
    {
      id: "raipur",
      slug: "raipur",
      label: "Raipur",
      labelHi: "रायपुर",
      sectionId: "raipur",
      href: "/category/raipur",
      matchers: [/raipur/i, /रायपुर/i],
      navOrder: 3,
    },
    {
      id: "politics",
      slug: "politics",
      label: "Politics",
      labelHi: "राजनीति",
      sectionId: "india",
      href: "/category/politics",
      matchers: [/politics/i, /election/i, /संसद/i, /सरकार/i, /राजनीति/i],
      navOrder: 4,
    },
    {
      id: "business",
      slug: "business",
      label: "Business",
      labelHi: "व्यापार",
      sectionId: "business",
      href: "/category/business",
      matchers: [/business/i, /economy/i, /market/i, /व्यापार/i, /शेयर/i],
      navOrder: 5,
    },
    {
      id: "technology",
      slug: "technology",
      label: "Tech & AI",
      labelHi: "तकनीक",
      sectionId: "business",
      href: "/category/technology",
      matchers: [/tech/i, /ai/i, /mobile/i, /smartphone/i, /तकनीक/i],
      navOrder: 6,
    },
    {
      id: "education",
      slug: "education",
      label: "Jobs & Education",
      labelHi: "शिक्षा व नौकरी",
      sectionId: "education",
      href: "/category/education",
      matchers: [/education/i, /job/i, /exam/i, /naukri/i, /शिक्षा/i, /नौकरी/i],
      navOrder: 7,
    },
    {
      id: "sports",
      slug: "sports",
      label: "Sports",
      labelHi: "खेल",
      sectionId: "sports",
      href: "/category/sports",
      matchers: [/sport/i, /cricket/i, /खेल/i],
      navOrder: 8,
    },
  ],
  regions: [
    {
      slug: "chhattisgarh",
      name: "Chhattisgarh",
      nameHi: "छत्तीसगढ़",
      priority: 1,
      routingWeight: 1,
      isPrimary: true,
    },
    {
      slug: "india",
      name: "India",
      nameHi: "भारत",
      priority: 1,
      routingWeight: 0.95,
    },
    {
      slug: "raipur",
      name: "Raipur",
      nameHi: "रायपुर",
      priority: 1,
      routingWeight: 0.9,
    },
    {
      slug: "bilaspur",
      name: "Bilaspur",
      nameHi: "बिलासपुर",
      priority: 2,
      routingWeight: 0.85,
    },
    {
      slug: "durg",
      name: "Durg-Bhilai",
      nameHi: "दुर्ग-भिलाई",
      priority: 2,
      routingWeight: 0.85,
    },
    {
      slug: "bastar",
      name: "Bastar",
      nameHi: "बस्तर",
      priority: 2,
      routingWeight: 0.8,
    },
    {
      slug: "delhi",
      name: "Delhi NCR",
      nameHi: "दिल्ली एनसीआर",
      priority: 2,
      routingWeight: 0.8,
    },
  ],
  newsroom: {
    defaultLanguage: "hi",
    enabledLanguages: ["hi", "en"],
    primaryRegionSlug: "chhattisgarh",
    regionalFirst: true,
    regionalBoostMultiplier: 1.15,
    timezone: "Asia/Kolkata",
    headerCity: "Raipur",
    headerCityHi: "रायपुर",
    editionLabel: "आज का अंक",
  },
  seo: {
    titleSuffix: "छत्तीसगढ़ और भारत | Jan Darpan",
    defaultDescription:
      "जन दर्पण: छत्तीसगढ़-आधारित डिजिटल समाचार मंच — रायपुर, बिलासपुर, बस्तर सहित सभी जिलों की ज़मीनी रिपोर्टिंग और देश भर के प्रमुख राष्ट्रीय घटनाक्रम।",
    keywords: [
      "Jan Darpan",
      "जन दर्पण",
      "Jan Darpan — Chhattisgarh & India",
      "जन दर्पण — छत्तीसगढ़ और भारत",
      "Chhattisgarh news",
      "छत्तीसगढ़ समाचार",
      "Raipur news",
      "Bilaspur news",
      "Bastar news",
      "India news",
      "National news India",
      "Breaking news India",
      "Top news in India",
      "भारत समाचार",
      "देश की ताज़ा खबरें",
      "हिंदी समाचार",
    ],
    locale: "hi_IN",
  },
  monetization: defaultMonetizationSettings(),
  updatedAt: new Date().toISOString(),
};
