import { defaultMonetizationSettings } from "@/lib/monetization/placements";
import type { TenantConfig } from "@/lib/tenant/types";

/** Example white-label client — demonstrates SaaS theming */
export const PIONEER_POST_TENANT: TenantConfig = {
  version: 1,
  id: "00000000-0000-4000-8000-000000000002",
  slug: "pioneer-post",
  status: "active",
  domains: ["pioneer.localhost", "pioneer-post.local"],
  siteUrl: "https://pioneer-post.local",
  branding: {
    nameEn: "Pioneer Post",
    nameHi: "पायनियर पोस्ट",
    taglineEn: "Maharashtra's digital daily",
    taglineHi: "महाराष्ट्र का डिजिटल अखबार",
    logoUrl: "/brand/pioneer-post-logo.svg",
    logoMarkUrl: "/brand/pioneer-post-mark.svg",
  },
  typography: {
    fontDisplay: "Playfair Display",
    fontBody: "Source Serif 4",
    fontMeta: "DM Mono",
    fontRegional: "Noto Serif Devanagari",
  },
  theme: {
    primary: "#1e3a8a",
    primaryDark: "#1e1b4b",
    accent: "#ea580c",
    accentSoft: "#fff7ed",
    live: "#e11d48",
    liveSoft: "#fff1f2",
    surface: "#f8fafc",
    ink: "#0f172a",
  },
  categories: [
    {
      id: "top-news",
      slug: "top-news",
      label: "Top News",
      labelHi: "टॉप",
      href: "#top-news",
      matchers: [],
      navOrder: 0,
    },
    {
      id: "mumbai",
      slug: "mumbai",
      label: "Mumbai",
      labelHi: "मुंबई",
      sectionId: "raipur",
      href: "/category/mumbai",
      matchers: [/mumbai/i, /मुंबई/i],
      navOrder: 1,
    },
    {
      id: "pune",
      slug: "pune",
      label: "Pune",
      labelHi: "पुणे",
      sectionId: "chhattisgarh",
      href: "/category/pune",
      matchers: [/pune/i, /पुणे/i],
      navOrder: 2,
    },
    {
      id: "politics",
      slug: "politics",
      label: "Politics",
      labelHi: "राजनीति",
      sectionId: "india",
      href: "/category/politics",
      matchers: [/politics/i, /शिवसेना/i, /बीजेपी/i],
      navOrder: 3,
    },
    {
      id: "business",
      slug: "business",
      label: "Business",
      labelHi: "व्यापार",
      sectionId: "business",
      href: "/category/business",
      matchers: [/business/i, /sensex/i],
      navOrder: 4,
    },
    {
      id: "sports",
      slug: "sports",
      label: "Sports",
      labelHi: "खेल",
      sectionId: "sports",
      href: "/category/sports",
      matchers: [/cricket/i, /ipl/i, /खेल/i],
      navOrder: 5,
    },
  ],
  regions: [
    {
      slug: "maharashtra",
      name: "Maharashtra",
      nameHi: "महाराष्ट्र",
      priority: 1,
      routingWeight: 1,
      isPrimary: true,
    },
    {
      slug: "mumbai",
      name: "Mumbai",
      nameHi: "मुंबई",
      priority: 1,
      routingWeight: 0.95,
    },
    {
      slug: "pune",
      name: "Pune",
      nameHi: "पुणे",
      priority: 2,
      routingWeight: 0.85,
    },
  ],
  newsroom: {
    defaultLanguage: "mr",
    enabledLanguages: ["mr", "hi", "en"],
    primaryRegionSlug: "maharashtra",
    regionalFirst: true,
    regionalBoostMultiplier: 1.2,
    timezone: "Asia/Kolkata",
    headerCity: "Mumbai",
    headerCityHi: "मुंबई",
    editionLabel: "Maharashtra",
  },
  seo: {
    titleSuffix: "Maharashtra News",
    defaultDescription:
      "Pioneer Post — AI-powered Maharashtra news with Marathi and Hindi editions.",
    keywords: ["Pioneer Post", "Maharashtra news", "Mumbai news", "Marathi news"],
    locale: "mr_IN",
  },
  monetization: defaultMonetizationSettings(),
  updatedAt: new Date().toISOString(),
};
