import type { BroadcastSegment } from "../types";

export const DURG_SOLAR_AD_SEGMENT: BroadcastSegment = {
  id: "ad-durg-solar-energy",
  slug: "ad-durg-solar-energy",
  headline: "दुर्ग सोलर — 3 kW मात्र ₹72,000* में, बिजली बिल से पाएं पूर्ण मुक्ति",
  headlineHi: "दुर्ग सोलर — 3 kW मात्र ₹72,000* में, बिजली बिल से पाएं पूर्ण मुक्ति",
  headlineEn: "Durg Solar — 3 kW Rooftop Solar System at ₹72,000*, Free from electricity bills",
  summary: "छत्तीसगढ़ में सोलर रूफटॉप लगवाएं। वारी सोलर 3 kW ₹72,000* और 5 kW ₹1,82,000*। संपर्क: +91 77778 12777 | durgsolar.com",
  summaryHi: "छत्तीसगढ़ में सोलर रूफटॉप लगवाएं। वारी सोलर 3 kW ₹72,000* और 5 kW ₹1,82,000*। संपर्क: +91 77778 12777 | durgsolar.com",
  summaryEn: "Install rooftop solar across Chhattisgarh. Waaree 3 kW ₹72,000*, 5 kW ₹1,82,000*. Contact +91 77778 12777 | durgsolar.com",
  imageUrl: "/jd-live/durg-solar-creative.png",
  categoryLabel: "विज्ञापन",
  categoryLabelHi: "विज्ञापन",
  categoryLabelEn: "Advertisement",
  district: "दुर्ग सोलर",
  districtHi: "दुर्ग सोलर",
  districtEn: "Durg Solar",
  section: "advertisement",
  isBreaking: false,
  isLive: false,
  priorityScore: 0,
  publishedAt: new Date().toISOString(),
  script: "यह विशेष संदेश दुर्ग सोलर एनर्जी द्वारा प्रायोजित है। अपने घर और प्रतिष्ठान पर सोलर पैनल लगवाएं और बिजली बिल से पूर्ण मुक्ति पाएं। वारी 3 किलोवाट सोलर सिस्टम सिर्फ 72,000 रुपये में उपलब्ध। अधिक जानकारी के लिए durgsolar.com पर जाएं या 77778 12777 पर कॉल करें।",
  durationSec: 14,
  isIntro: false,
  isAd: true,
  adCampaign: "durg_solar_rooftop",
  adUrl: "https://durgsolar.com",
};
