/** Hindi-first strings for Post News / My News. Every key exists in both languages (a test enforces it). */

export type UserNewsLocale = "hi" | "en";

const hi = {
  postNews: "समाचार पोस्ट करें",
  myNews: "मेरी खबरें",
  verifiedBadge: "सत्यापित",
  notVerifiedBadge: "सत्यापन बाकी",
  verifyToPost: "समाचार प्रकाशित करने के लिए पहचान सत्यापित करें",
  verificationUnavailable: "पहचान सत्यापन तब तक उपलब्ध नहीं है जब तक सत्यापन सेवा कॉन्फ़िगर नहीं हो जाती।",
  signInToPost: "समाचार पोस्ट करने के लिए साइन इन करें",
  postNewsSub: "अपनी बात बोलकर या लिखकर बताइए। हम खबर का ड्राफ्ट बनाएंगे, आप जाँचकर मंज़ूर करेंगे।",
  openPostNews: "खबर भेजना शुरू करें",
  openMyNews: "मेरी खबरें देखें",
  step1: "खबर बताइए",
  step2: "फोटो / वीडियो जोड़ें",
  step3: "AI ड्राफ्ट बनाएं",
  step4: "जाँचें और मंज़ूर करें",
  step5: "जमा करें",
  langLabel: "खबर की भाषा",
  hindi: "हिंदी",
  english: "English",
  tellPlaceholder: "क्या हुआ, कहाँ और कब? जो आपने देखा या जाना, वही लिखिए।",
  location: "स्थान (शहर/कस्बा)",
  district: "ज़िला (यदि पता हो)",
  noDistrict: "— चुनें —",
  recordVoice: "आवाज़ रिकॉर्ड करें",
  stopRecording: "रिकॉर्डिंग रोकें",
  recording: "रिकॉर्ड हो रहा है…",
  voiceUnavailable: "आवाज़ से खबर अभी उपलब्ध नहीं है। कृपया लिखकर बताएं।",
  voiceUnsupportedBrowser: "इस ब्राउज़र में रिकॉर्डिंग काम नहीं करती। Chrome, Edge या Firefox आज़माएं, या लिखकर बताएं।",
  voiceMax: "अधिकतम 1 मिनट",
  transcript: "आपकी रिकॉर्डिंग से बना पाठ (ज़रूरत हो तो सुधारें)",
  continue: "आगे बढ़ें",
  back: "पीछे",
  skip: "छोड़ें",
  addImage: "फोटो जोड़ें (चौड़ी, लैंडस्केप)",
  addVideo: "वीडियो जोड़ें (चौड़ा, अधिकतम 3 मिनट)",
  mediaHint: "सिर्फ़ चौड़े (लैंडस्केप) फोटो/वीडियो स्वीकार हैं। फोटो से लोकेशन जैसी निजी जानकारी हटा दी जाती है।",
  uploading: "अपलोड हो रहा है…",
  checking: "जाँच हो रही है…",
  ready: "तैयार",
  rejected: "स्वीकार नहीं हुआ",
  pendingCheck: "जाँच लंबित",
  remove: "हटाएं",
  createDraft: "AI ड्राफ्ट बनाएं",
  drafting: "ड्राफ्ट बन रहा है… इसमें आधा मिनट लग सकता है",
  aiBanner: "AI की मदद से बना ड्राफ्ट। प्रकाशित करने से पहले कृपया तथ्य जाँच लें।",
  headline: "शीर्षक",
  subheadline: "उप-शीर्षक",
  summary: "सारांश",
  body: "खबर",
  saveChanges: "बदलाव सहेजें",
  saved: "सहेजा गया",
  approve: "मैंने जाँच लिया, मंज़ूर करें",
  approved: "आपने यह खबर मंज़ूर कर दी है",
  submit: "मॉडरेशन के लिए जमा करें",
  submittedTitle: "खबर जमा हो गई",
  submittedBody: "हमारे संपादक इसकी समीक्षा करेंगे। मंज़ूरी के बाद ही यह प्रकाशित होगी। आप 'मेरी खबरें' में स्थिति देख सकते हैं।",
  editToApprove: "बदलाव करने पर आपको दोबारा मंज़ूर करना होगा।",
  problems: "इन्हें ठीक करें",
  blockingFacts: "AI ने ये जानकारी जोड़ी है जो आपने नहीं बताई — इसे हटाएं",
  riskBlock: "यह जानकारी प्रकाशित नहीं की जा सकती (जैसे फोन नंबर, ईमेल या पहचान संख्या)",
  riskReview: "संपादक इन बातों की अलग से जाँच करेंगे",
  placeFound: "स्थान पहचाना गया",
  placeUnknown: "स्थान स्पष्ट नहीं है — कृपया खबर में शहर/ज़िले का नाम लिखें",
  districtUnverified: "आपने जो ज़िला चुना, उसका ज़िक्र खबर में नहीं है। संपादक पुष्टि करेंगे।",
  withdraw: "वापस लें",
  withdrawConfirm: "क्या आप यह खबर वापस लेना चाहते हैं?",
  loading: "लोड हो रहा है…",
  error: "कुछ गड़बड़ हुई। कृपया दोबारा कोशिश करें।",
  filterAll: "सभी",
  filterPublished: "प्रकाशित",
  filterPending: "समीक्षा में",
  filterRejected: "अस्वीकृत",
  filterDraft: "ड्राफ्ट",
  noStories: "अभी कोई खबर नहीं",
  views: "व्यू",
  viewsToday: "आज",
  views7d: "7 दिन",
  uniqueViewers: "अलग-अलग पाठक",
  likes: "पसंद",
  comments: "टिप्पणियाँ",
  engagement: "एंगेजमेंट दर",
  publishedOn: "प्रकाशित",
  moderatorNote: "संपादक का संदेश",
  revenueNotActive: "विज्ञापन राजस्व साझेदारी अभी सक्रिय नहीं है",
  continueEditing: "संपादित करें",
  openStory: "खबर देखें",
} as const;

const en: Record<keyof typeof hi, string> = {
  postNews: "POST NEWS",
  myNews: "My News",
  verifiedBadge: "Verified",
  notVerifiedBadge: "Not verified",
  verifyToPost: "Verify your identity to publish news",
  verificationUnavailable: "Identity verification unavailable until verification service is configured.",
  signInToPost: "Sign in to post news",
  postNewsSub: "Tell us what happened by voice or text. We prepare a draft, you check it, and our editors review it before anything is published.",
  openPostNews: "Start a news report",
  openMyNews: "View My News",
  step1: "Tell us the news",
  step2: "Add photo / video",
  step3: "AI creates a draft",
  step4: "Review and approve",
  step5: "Submit",
  langLabel: "Language of the story",
  hindi: "हिंदी",
  english: "English",
  tellPlaceholder: "What happened, where and when? Write only what you saw or know.",
  location: "Place (town / area)",
  district: "District (if you know it)",
  noDistrict: "— choose —",
  recordVoice: "Record voice",
  stopRecording: "Stop recording",
  recording: "Recording…",
  voiceUnavailable: "Voice reports are not available yet. Please type your report.",
  voiceUnsupportedBrowser: "Recording does not work in this browser. Try Chrome, Edge or Firefox, or type your report.",
  voiceMax: "Up to 1 minute",
  transcript: "Text from your recording (correct it if needed)",
  continue: "Continue",
  back: "Back",
  skip: "Skip",
  addImage: "Add a photo (wide, landscape)",
  addVideo: "Add a video (wide, up to 3 minutes)",
  mediaHint: "Only wide (landscape) photos and videos are accepted. Private details such as location data are removed from photos.",
  uploading: "Uploading…",
  checking: "Checking…",
  ready: "Ready",
  rejected: "Not accepted",
  pendingCheck: "Check pending",
  remove: "Remove",
  createDraft: "Create AI draft",
  drafting: "Creating your draft… this can take up to half a minute",
  aiBanner: "AI-assisted draft. Please verify the facts before publishing.",
  headline: "Headline",
  subheadline: "Sub-headline",
  summary: "Summary",
  body: "Story",
  saveChanges: "Save changes",
  saved: "Saved",
  approve: "I have checked it — approve",
  approved: "You have approved this story",
  submit: "Submit for moderation",
  submittedTitle: "Story submitted",
  submittedBody: "Our editors will review it. It is published only after they approve it. You can follow its status in My News.",
  editToApprove: "If you change anything you will need to approve it again.",
  problems: "Please fix these",
  blockingFacts: "The AI added details you did not give us — remove them",
  riskBlock: "This cannot be published (for example a phone number, email address or ID number)",
  riskReview: "Editors will look at these points separately",
  placeFound: "Place recognised",
  placeUnknown: "The place is not clear — please name the town or district in the story",
  districtUnverified: "The district you picked is not mentioned in the story. An editor will confirm it.",
  withdraw: "Withdraw",
  withdrawConfirm: "Do you want to withdraw this story?",
  loading: "Loading…",
  error: "Something went wrong. Please try again.",
  filterAll: "All",
  filterPublished: "Published",
  filterPending: "Pending",
  filterRejected: "Rejected",
  filterDraft: "Drafts",
  noStories: "No stories yet",
  views: "Views",
  viewsToday: "Today",
  views7d: "7 days",
  uniqueViewers: "Unique readers",
  likes: "Likes",
  comments: "Comments",
  engagement: "Engagement rate",
  publishedOn: "Published",
  moderatorNote: "Editor's note",
  revenueNotActive: "Advertising revenue sharing not active",
  continueEditing: "Edit",
  openStory: "Open story",
};

export const USER_NEWS_STRINGS: Record<UserNewsLocale, Record<keyof typeof hi, string>> = { hi, en };
export type UserNewsStringKey = keyof typeof hi;

export function tUserNews(locale: UserNewsLocale, key: UserNewsStringKey): string {
  return USER_NEWS_STRINGS[locale][key] ?? USER_NEWS_STRINGS.en[key];
}

/** Plain-language labels for fact and risk flag codes. */
export const FLAG_LABELS: Record<string, { hi: string; en: string }> = {
  unsupported_number: { hi: "संख्या जो आपने नहीं बताई", en: "A number you did not give" },
  unsupported_quote: { hi: "उद्धरण जो आपने नहीं बताया", en: "A quotation you did not give" },
  unsupported_date: { hi: "तारीख जो आपने नहीं बताई", en: "A date you did not give" },
  unsupported_actor: { hi: "किसी का बयान/मौजूदगी जो आपने नहीं बताई", en: "A statement or witness you did not mention" },
  unsupported_name: { hi: "नाम जो आपने नहीं बताया", en: "A name you did not give" },
  low_source_overlap: { hi: "ड्राफ्ट में बहुत नई बातें हैं", en: "The draft has a lot of new wording" },
  personal_data_exposure: { hi: "निजी जानकारी", en: "Personal information" },
  sexual_content: { hi: "अश्लील सामग्री", en: "Explicit content" },
  violence: { hi: "हिंसा का वर्णन", en: "Violence" },
  harmful_accusation: { hi: "किसी पर आरोप तथ्य की तरह लिखा है", en: "An accusation stated as fact" },
  defamatory_claim: { hi: "मानहानि का जोखिम", en: "Defamation risk" },
  unverifiable_claim: { hi: "अपुष्ट दावा", en: "Unverified claim" },
  misinformation_risk: { hi: "गलत जानकारी का जोखिम", en: "Misinformation risk" },
  spam: { hi: "स्पैम जैसा", en: "Looks like spam" },
  duplicate: { hi: "मिलती-जुलती खबर पहले से है", en: "Similar story already exists" },
  manipulated_media: { hi: "मीडिया से छेड़छाड़ का संदेह", en: "Possible manipulated media" },
  copyright_problem: { hi: "कॉपीराइट की समस्या", en: "Copyright problem" },
};

export function flagLabel(code: string, locale: UserNewsLocale): string {
  return FLAG_LABELS[code]?.[locale] ?? code.replace(/_/g, " ");
}
