/**
 * Editorial Trust view-model — canonical server-side trust projection.
 * Reuses editorial intelligence outputs; no AI calls, no invented scores.
 */

import { getDictionary } from "@/lib/i18n/dictionaries";
import type { NewsroomLanguage } from "@/lib/i18n/languages";
import type { EventViewModel } from "@/lib/events/event-view-model";
import type { StoryAttribution } from "@/lib/news/story-view";
import type {
  EditorialIntelligenceVm,
  EditorialQualityBadge,
} from "@/lib/story/editorial-intelligence";
import type { EditorialMetadata, GeneratedArticleRow } from "@/lib/types/newsroom";
import type { NewsArticleRow } from "@/lib/types/news-article";

export type EditorialTrustVm = {
  trustLevel: string | null;
  editorialStatus: string | null;
  reviewStatus: string | null;
  sourceSummaryLines: string[];
  sourceCount: number;
  officialSourceCount: number;
  verificationState: string | null;
  confidence: number | null;
  confidenceLabel: string | null;
  clusterConfidenceLabel: string | null;
  publishedAtIso: string | null;
  publishedAtLabel: string | null;
  lastUpdatedIso: string | null;
  lastUpdatedLabel: string | null;
  showUpdateHistory: boolean;
  aiDisclosureLines: string[];
  changeHistorySummary: string | null;
  badges: EditorialQualityBadge[];
  hasLayer: boolean;
};

export type BuildEditorialTrustInput = {
  article: NewsArticleRow;
  editorialMeta?: EditorialMetadata | null;
  generatedRow?: GeneratedArticleRow | null;
  attribution: StoryAttribution;
  publishedAtLabel: string | null;
  updatedAtLabel: string | null;
  displayLanguage: NewsroomLanguage;
  editorialVm: EditorialIntelligenceVm;
  eventViewModel?: EventViewModel | null;
};

function formatStatusLabel(status: string | null | undefined): string | null {
  if (!status?.trim()) return null;
  return status.charAt(0).toUpperCase() + status.slice(1).toLowerCase();
}

export function resolvePublishDecisionLabel(
  decision: string | null | undefined
): string | null {
  if (!decision?.trim()) return null;
  const normalized = decision.trim().toLowerCase();
  if (normalized === "publish") return "Cleared for publication";
  if (normalized === "repair") return "Editorially repaired before publication";
  return null;
}

export function resolveWorkflowReviewStatus(
  generatedRow?: GeneratedArticleRow | null
): string | null {
  const workflow = (
    generatedRow as (GeneratedArticleRow & { workflow_status?: string | null }) | null
  )?.workflow_status;
  if (!workflow?.trim()) return null;

  const normalized = workflow.trim().toLowerCase();
  if (normalized === "published") return "Published through newsroom workflow";
  if (normalized === "scheduled") return "Scheduled through newsroom workflow";
  if (normalized === "draft") return null;
  return formatStatusLabel(workflow);
}

function buildSourceSummaryLines(
  editorialVm: EditorialIntelligenceVm,
  sourceCount: number
): string[] {
  const lines: string[] = [];
  const officialCount = editorialVm.sources.filter(
    (source) => source.kind === "official"
  ).length;
  const reportingCount = Math.max(sourceCount - officialCount, 0);

  if (reportingCount > 1) {
    lines.push(`${reportingCount} reporting sources`);
  } else if (reportingCount === 1) {
    lines.push("1 reporting source");
  }

  if (officialCount > 1) {
    lines.push(`${officialCount} official sources`);
  } else if (officialCount === 1) {
    lines.push("1 official source");
  }

  if (editorialVm.officialSource && !officialCount) {
    lines.push("Official source cited");
  }

  return lines;
}

function buildAiDisclosureLines(
  editorialMeta: EditorialMetadata | null | undefined,
  editorialVm: EditorialIntelligenceVm,
  generatedRow?: GeneratedArticleRow | null
): string[] {
  const lines: string[] = [];

  if (editorialMeta?.model?.trim()) {
    lines.push("AI-assisted editorial draft");
  } else if (editorialVm.flags.aiGenerated) {
    lines.push("AI-assisted editorial draft");
  }

  if (editorialMeta?.intelligence_v2) {
    lines.push("Editorial Intelligence metadata included");
  }

  if (editorialVm.flags.humanReviewed) {
    lines.push("Reviewed through newsroom workflow");
  }

  const workflowLine = resolveWorkflowReviewStatus(generatedRow);
  if (workflowLine && !editorialVm.flags.humanReviewed) {
    lines.push(workflowLine);
  }

  if (editorialMeta?.repaired) {
    lines.push("Editorially repaired before publication");
  }

  return [...new Set(lines)];
}

export function resolveEditorialChangeHistorySummary(
  editorialMeta: EditorialMetadata | null | undefined
): string | null {
  if (editorialMeta?.regenerated_at?.trim()) {
    return "This article was regenerated by the newsroom desk";
  }
  if (editorialMeta?.translations_updated_at?.trim()) {
    return "Translation metadata was updated after publication";
  }
  return null;
}

function resolveTrustLevel(
  editorialMeta: EditorialMetadata | null | undefined,
  editorialVm: EditorialIntelligenceVm,
  displayLanguage: NewsroomLanguage
): string | null {
  const t = getDictionary(displayLanguage);
  const confidence = editorialMeta?.ai_confidence;

  if (typeof confidence === "number" && confidence >= 0.82) {
    return t.trust.verified;
  }
  if (editorialMeta?.is_breaking || editorialMeta?.breaking_override) {
    return t.trust.fastUpdates;
  }
  return null;
}

export function buildEditorialTrust(
  input: BuildEditorialTrustInput
): EditorialTrustVm {
  const {
    article,
    editorialMeta,
    generatedRow,
    attribution,
    publishedAtLabel,
    updatedAtLabel,
    displayLanguage,
    editorialVm,
    eventViewModel,
  } = input;

  const sourceCount = Math.max(
    attribution.sourceCount,
    editorialMeta?.source_count ?? 0,
    editorialVm.sources.length
  );

  const officialSourceCount = editorialVm.sources.filter(
    (source) => source.kind === "official"
  ).length;

  const publishedAtIso = article.published_at;
  const lastUpdatedIso = editorialVm.readingInfo.updatedAtIso;
  const showUpdateHistory = Boolean(
    publishedAtIso &&
      lastUpdatedIso &&
      publishedAtIso !== lastUpdatedIso &&
      (publishedAtLabel || updatedAtLabel)
  );

  const confidence = editorialVm.readingInfo.confidence;
  const confidenceLabel = editorialVm.readingInfo.confidenceLabel;
  const clusterConfidenceLabel =
    eventViewModel?.coverage_statistics.cluster_confidence_label
      ? eventViewModel.coverage_statistics.cluster_confidence_label
          .charAt(0)
          .toUpperCase() +
        eventViewModel.coverage_statistics.cluster_confidence_label.slice(1)
      : null;

  const badges = editorialVm.qualityBadges;
  const sourceSummaryLines = buildSourceSummaryLines(editorialVm, sourceCount);
  const aiDisclosureLines = buildAiDisclosureLines(
    editorialMeta,
    editorialVm,
    generatedRow
  );
  const changeHistorySummary = resolveEditorialChangeHistorySummary(editorialMeta);
  const verificationState = resolvePublishDecisionLabel(
    editorialMeta?.publish_decision
  );

  const reviewStatus =
    generatedRow?.editorial_status === "approved"
      ? getDictionary(displayLanguage).trust.reviewed
      : formatStatusLabel(generatedRow?.editorial_status);

  const hasLayer = Boolean(
    badges.length ||
      sourceSummaryLines.length ||
      showUpdateHistory ||
      aiDisclosureLines.length ||
      confidenceLabel ||
      clusterConfidenceLabel ||
      changeHistorySummary ||
      verificationState ||
      resolveTrustLevel(editorialMeta, editorialVm, displayLanguage)
  );

  return {
    trustLevel: resolveTrustLevel(editorialMeta, editorialVm, displayLanguage),
    editorialStatus: formatStatusLabel(generatedRow?.editorial_status),
    reviewStatus,
    sourceSummaryLines,
    sourceCount,
    officialSourceCount,
    verificationState,
    confidence,
    confidenceLabel,
    clusterConfidenceLabel,
    publishedAtIso,
    publishedAtLabel,
    lastUpdatedIso,
    lastUpdatedLabel: updatedAtLabel,
    showUpdateHistory,
    aiDisclosureLines,
    changeHistorySummary,
    badges,
    hasLayer,
  };
}
